openapi: "3.0.0"
info:
  title: "Fapa-Store RESTful API"
  description: "This is a list endpoint of Transaction Service"
  version: "1.0.0"
  contact:
    name: Developer
    email: "raygakertia1@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "https://staging.fapastore.com/api/v1"
  - url: "https://fapasotre.com/api/v1"
paths:
  /transaction:
    get:
      summary: "Get list of all transaction"
      description: "This is a endpoint for get list of transaction. Used for 'admin' for get all transaction or for 'user' for get their history transaction"
      parameters:
        - name: "user_id"
          description: "Get all transaction for specific user."
          required: false
          in: "query"
          schema:
            type: "string"
        - name: "limit"
          description: "For pagination, default limit is '10'"
          required: false
          in: "query"
          schema:
            type: "number"
        - name: "page"
          description: "For pagination, start from '1'"
          required: false
          in: "query"
          schema:
            type: "number"
      responses:
        200:
          description: "Get list transaction success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "string"
                    default: "success"
                  message:
                    type: "string"
                    default: "Success"
                  data:
                    type: "object"
                    properties:
                      meta:
                        type: "object"
                        properties:
                          page:
                            type: "number"
                            default: 1
                          row_per_page:
                            type: "number"
                            default: 10
                          next_page:
                            type: "boolean"
                            default: false
                          previous:
                            type: "boolean"
                            default: false
                      transactions:
                        type: "array"
                        items:
                          type: "object"
                          properties:
                            id:
                              type: "number"
                            user_id:
                              type: "number"
                            cart_id:
                              type: "number"
                            courier:
                              type: "string"
                              default: "JNE"
                            payment_method:
                              type: "string"
                              default: "midtrans"
                            payment_url:
                              type: "string"
                              default: "http://example.com"
                            total_price:
                              type: "number"
                            status:
                              type: "string"
                              default: "SUCCESS"
                            created_at:
                              type: "string"
                              default: "2021-11-01T12:42:14.429+07:00"

        
    post:
      summary: "Create transaction"
      description: "Create new transaction from users"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                user_id:
                  type: "number"
                  required: true
                cart_id:
                  type: "number"
                  required: true
                courier:
                  type: "string"
                  required: true
                payment_method:
                  type: "string"
                  required: true
                total_price:
                  type: "number"
                  format: "float"
                  required: true
      responses:
        201:
          description: "Create transaction success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "string"
                    default: "success"
                  message:
                    type: "string"
                    default: "Success"
                  data:
                    type: "string"
                    default: "url payment midtrans"
        
  /transaction/{transactionId}:
    get:
      summary: "Get details of transaction"
      description: "Get details of transcation"
      parameters:
        - name: "transactionId"
          description: "Transaction ID"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "Get details transaction success"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  code:
                    type: "string"
                    default: "success"
                  message:
                    type: "string"
                    default: "Success"
                  data:
                    type: "object"
                    properties:
                      id:
                        type: "number"
                      user_id:
                        type: "number"
                      cart_id:
                        type: "number"
                      courier:
                        type: "string"
                        default: "JNE"
                      payment_method:
                        type: "string"
                        default: "bank_transfer"
                      payment_url:
                        type: "string"
                        default: ""
                      total_price:
                        type: "number"
                      status:
                        type: "string"
                        default: "PENDING"
                      created_at:
                        type: "string"
                        default: "2021-11-01T12:42:14.429+07:00"
        
    put:
      summary: "Update transaction user"
      description: "Update transaction, only 'status' can be updated by admin"
      parameters:
        - name: "transactionId"
          description: "Transaction ID"
          required: true
          in: "path"
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                status:
                  type: "string"
                  required: true
                  default: "SUCCESS|FAILED|etc"
      responses:
        200:
          description: "Update transaction success"
          content:
            application/json:
                schema:
                  type: "object"
                  properties:
                    code:
                      type: "string"
                      default: "success"
                    message:
                      type: "string"
                      default: "Success"
                    data:
                      type: "object"
    
    delete:
      summary: "Delete transaction"
      description: "Soft delete transaction, can be used only for 'admin'"
      parameters:
        - name: "transactionId"
          description: "Transaction ID"
          required: true
          in: "path"
          schema:
            type: "string"
      responses:
        200:
          description: "Delete transaction success"
          content:
            application/json:
                schema:
                  type: "object"
                  properties:
                    code:
                      type: "string"
                      default: "success"
                    message:
                      type: "string"
                      default: "Success"
                    data:
                      type: "object"