package mocks

import (
	cart "go-hexagonal/business/cart"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

func (_m *Repository) FindCartByUserId(userId int) (*cart.Cart, error) {
	ret := _m.Called(userId)

	var r0 *cart.Cart
	if rf, ok := ret.Get(0).(func(int) *cart.Cart); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *Repository) InsertCart(_a0 cart.Cart) (int, error) {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(cart.Cart) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	var r1 *cart.Cart
	if rf, ok := ret.Get(0).(func(cart.Cart) *cart.Cart); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r1 = ret.Get(0).(*cart.Cart)
		}
	}

	return r1.Id, r0
}

func (_m *Repository) InsertCartDetails(cartDetail cart.CartDetails) error {
	return nil
}

func (_m *Repository) CheckCartProduct(cartId int, productId int) (bool, error) {

	return false, nil
}

func (_m *Repository) UpdateCartDetailsProduct(cartId int, productId int) error {
	return nil
}

func (_m *Repository) DeleteCartDetails(cartId int, productId int) error {
	ret := _m.Called(cartId, productId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(cartId, productId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *Repository) UpdateQuantityCartDetails(cartId int, productId int, quantity int) error {
	ret := _m.Called(cartId, productId, quantity)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int, int) error); ok {
		r0 = rf(cartId, productId, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
