name: ci/cd process

on:
  push:
    branches: 
      - 'test-deploy-fadel'

jobs:
  unit-test:
    name: unittest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: running unit test
      run: go test ./... -cover
  

